// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: runner.proto

package runnerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RunnerService_GetJob_FullMethodName       = "/runkite.runner.v0.RunnerService/GetJob"
	RunnerService_StreamEvents_FullMethodName = "/runkite.runner.v0.RunnerService/StreamEvents"
	RunnerService_ReportStatus_FullMethodName = "/runkite.runner.v0.RunnerService/ReportStatus"
	RunnerService_WatchCancels_FullMethodName = "/runkite.runner.v0.RunnerService/WatchCancels"
	RunnerService_Heartbeat_FullMethodName    = "/runkite.runner.v0.RunnerService/Heartbeat"
)

// RunnerServiceClient is the client API for RunnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RunnerService is the gRPC service that runners implement.
// The control plane connects to runners (long-poll style) or runners
// connect to the control plane -- either way, this is the contract.
type RunnerServiceClient interface {
	// GetJob blocks until a job is available for the runner.
	// Runner calls this in a loop (long-poll pattern).
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error)
	// StreamEvents is called by the runner to stream events back
	// to the control plane for a specific run.
	StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RunEventProto, StreamEventsResponse], error)
	// ReportStatus reports the final status of a run.
	ReportStatus(ctx context.Context, in *ReportStatusRequest, opts ...grpc.CallOption) (*ReportStatusResponse, error)
	// WatchCancels is a server-streaming RPC the runner calls to receive
	// cancel signals for runs it is executing. The runner sends its
	// runner_kind; the server streams CancelSignal messages whenever
	// a run of that kind is cancelled.
	WatchCancels(ctx context.Context, in *WatchCancelsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CancelSignal], error)
	// Heartbeat is called periodically by the runner while a run is
	// actively executing, to prove liveness for the WHOLE run, not just
	// delivery. Without this, the control plane only knows a job is alive
	// up to its first StreamEvents message (~15ms after dequeue in
	// practice) -- a runner crash any time after that left the run
	// permanently stuck, confirmed live. The server extends the same
	// in-flight lease Dequeue creates (see transport.JobQueue's Renew)
	// each time this arrives; a runner that stops heartbeating (crashed,
	// or an older runner that doesn't send this RPC at all) eventually
	// falls stale and gets reclaimed by the existing ReclaimStale reaper
	// -- no new reclaim mechanism needed, just a mechanism to keep
	// resetting the clock during real work.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type runnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRunnerServiceClient(cc grpc.ClientConnInterface) RunnerServiceClient {
	return &runnerServiceClient{cc}
}

func (c *runnerServiceClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobResponse)
	err := c.cc.Invoke(ctx, RunnerService_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RunEventProto, StreamEventsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RunnerService_ServiceDesc.Streams[0], RunnerService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunEventProto, StreamEventsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunnerService_StreamEventsClient = grpc.ClientStreamingClient[RunEventProto, StreamEventsResponse]

func (c *runnerServiceClient) ReportStatus(ctx context.Context, in *ReportStatusRequest, opts ...grpc.CallOption) (*ReportStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportStatusResponse)
	err := c.cc.Invoke(ctx, RunnerService_ReportStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) WatchCancels(ctx context.Context, in *WatchCancelsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CancelSignal], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RunnerService_ServiceDesc.Streams[1], RunnerService_WatchCancels_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchCancelsRequest, CancelSignal]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunnerService_WatchCancelsClient = grpc.ServerStreamingClient[CancelSignal]

func (c *runnerServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, RunnerService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunnerServiceServer is the server API for RunnerService service.
// All implementations must embed UnimplementedRunnerServiceServer
// for forward compatibility.
//
// RunnerService is the gRPC service that runners implement.
// The control plane connects to runners (long-poll style) or runners
// connect to the control plane -- either way, this is the contract.
type RunnerServiceServer interface {
	// GetJob blocks until a job is available for the runner.
	// Runner calls this in a loop (long-poll pattern).
	GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error)
	// StreamEvents is called by the runner to stream events back
	// to the control plane for a specific run.
	StreamEvents(grpc.ClientStreamingServer[RunEventProto, StreamEventsResponse]) error
	// ReportStatus reports the final status of a run.
	ReportStatus(context.Context, *ReportStatusRequest) (*ReportStatusResponse, error)
	// WatchCancels is a server-streaming RPC the runner calls to receive
	// cancel signals for runs it is executing. The runner sends its
	// runner_kind; the server streams CancelSignal messages whenever
	// a run of that kind is cancelled.
	WatchCancels(*WatchCancelsRequest, grpc.ServerStreamingServer[CancelSignal]) error
	// Heartbeat is called periodically by the runner while a run is
	// actively executing, to prove liveness for the WHOLE run, not just
	// delivery. Without this, the control plane only knows a job is alive
	// up to its first StreamEvents message (~15ms after dequeue in
	// practice) -- a runner crash any time after that left the run
	// permanently stuck, confirmed live. The server extends the same
	// in-flight lease Dequeue creates (see transport.JobQueue's Renew)
	// each time this arrives; a runner that stops heartbeating (crashed,
	// or an older runner that doesn't send this RPC at all) eventually
	// falls stale and gets reclaimed by the existing ReclaimStale reaper
	// -- no new reclaim mechanism needed, just a mechanism to keep
	// resetting the clock during real work.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	mustEmbedUnimplementedRunnerServiceServer()
}

// UnimplementedRunnerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunnerServiceServer struct{}

func (UnimplementedRunnerServiceServer) GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedRunnerServiceServer) StreamEvents(grpc.ClientStreamingServer[RunEventProto, StreamEventsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedRunnerServiceServer) ReportStatus(context.Context, *ReportStatusRequest) (*ReportStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportStatus not implemented")
}
func (UnimplementedRunnerServiceServer) WatchCancels(*WatchCancelsRequest, grpc.ServerStreamingServer[CancelSignal]) error {
	return status.Error(codes.Unimplemented, "method WatchCancels not implemented")
}
func (UnimplementedRunnerServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedRunnerServiceServer) mustEmbedUnimplementedRunnerServiceServer() {}
func (UnimplementedRunnerServiceServer) testEmbeddedByValue()                       {}

// UnsafeRunnerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunnerServiceServer will
// result in compilation errors.
type UnsafeRunnerServiceServer interface {
	mustEmbedUnimplementedRunnerServiceServer()
}

func RegisterRunnerServiceServer(s grpc.ServiceRegistrar, srv RunnerServiceServer) {
	// If the following call panics, it indicates UnimplementedRunnerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RunnerService_ServiceDesc, srv)
}

func _RunnerService_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RunnerServiceServer).StreamEvents(&grpc.GenericServerStream[RunEventProto, StreamEventsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunnerService_StreamEventsServer = grpc.ClientStreamingServer[RunEventProto, StreamEventsResponse]

func _RunnerService_ReportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).ReportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_ReportStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).ReportStatus(ctx, req.(*ReportStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_WatchCancels_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchCancelsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RunnerServiceServer).WatchCancels(m, &grpc.GenericServerStream[WatchCancelsRequest, CancelSignal]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunnerService_WatchCancelsServer = grpc.ServerStreamingServer[CancelSignal]

func _RunnerService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RunnerService_ServiceDesc is the grpc.ServiceDesc for RunnerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunnerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runkite.runner.v0.RunnerService",
	HandlerType: (*RunnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetJob",
			Handler:    _RunnerService_GetJob_Handler,
		},
		{
			MethodName: "ReportStatus",
			Handler:    _RunnerService_ReportStatus_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _RunnerService_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _RunnerService_StreamEvents_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "WatchCancels",
			Handler:       _RunnerService_WatchCancels_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "runner.proto",
}
