// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: runner.proto

package runnerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetJobRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RunnerKind     string                 `protobuf:"bytes,1,opt,name=runner_kind,json=runnerKind,proto3" json:"runner_kind,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // how long to wait for a job
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{0}
}

func (x *GetJobRequest) GetRunnerKind() string {
	if x != nil {
		return x.RunnerKind
	}
	return ""
}

func (x *GetJobRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type GetJobResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HasJob         bool                   `protobuf:"varint,1,opt,name=has_job,json=hasJob,proto3" json:"has_job,omitempty"`
	AssignmentJson string                 `protobuf:"bytes,2,opt,name=assignment_json,json=assignmentJson,proto3" json:"assignment_json,omitempty"` // JSON-encoded RunAssignment
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{1}
}

func (x *GetJobResponse) GetHasJob() bool {
	if x != nil {
		return x.HasJob
	}
	return false
}

func (x *GetJobResponse) GetAssignmentJson() string {
	if x != nil {
		return x.AssignmentJson
	}
	return ""
}

type RunEventProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	EventJson     string                 `protobuf:"bytes,2,opt,name=event_json,json=eventJson,proto3" json:"event_json,omitempty"` // JSON-encoded RunEvent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunEventProto) Reset() {
	*x = RunEventProto{}
	mi := &file_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunEventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunEventProto) ProtoMessage() {}

func (x *RunEventProto) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunEventProto.ProtoReflect.Descriptor instead.
func (*RunEventProto) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{2}
}

func (x *RunEventProto) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunEventProto) GetEventJson() string {
	if x != nil {
		return x.EventJson
	}
	return ""
}

type StreamEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsResponse) Reset() {
	*x = StreamEventsResponse{}
	mi := &file_runner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsResponse) ProtoMessage() {}

func (x *StreamEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsResponse.ProtoReflect.Descriptor instead.
func (*StreamEventsResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{3}
}

func (x *StreamEventsResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ReportStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                 // "success", "error", "interrupted"
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // only if status == "error"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStatusRequest) Reset() {
	*x = ReportStatusRequest{}
	mi := &file_runner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusRequest) ProtoMessage() {}

func (x *ReportStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportStatusRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{4}
}

func (x *ReportStatusRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ReportStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportStatusRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ReportStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStatusResponse) Reset() {
	*x = ReportStatusResponse{}
	mi := &file_runner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusResponse) ProtoMessage() {}

func (x *ReportStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportStatusResponse) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{5}
}

func (x *ReportStatusResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type WatchCancelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunnerKind    string                 `protobuf:"bytes,1,opt,name=runner_kind,json=runnerKind,proto3" json:"runner_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchCancelsRequest) Reset() {
	*x = WatchCancelsRequest{}
	mi := &file_runner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchCancelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchCancelsRequest) ProtoMessage() {}

func (x *WatchCancelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchCancelsRequest.ProtoReflect.Descriptor instead.
func (*WatchCancelsRequest) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{6}
}

func (x *WatchCancelsRequest) GetRunnerKind() string {
	if x != nil {
		return x.RunnerKind
	}
	return ""
}

type CancelSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSignal) Reset() {
	*x = CancelSignal{}
	mi := &file_runner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSignal) ProtoMessage() {}

func (x *CancelSignal) ProtoReflect() protoreflect.Message {
	mi := &file_runner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSignal.ProtoReflect.Descriptor instead.
func (*CancelSignal) Descriptor() ([]byte, []int) {
	return file_runner_proto_rawDescGZIP(), []int{7}
}

func (x *CancelSignal) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

var File_runner_proto protoreflect.FileDescriptor

const file_runner_proto_rawDesc = "" +
	"\n" +
	"\frunner.proto\x12\x11runkite.runner.v0\"Y\n" +
	"\rGetJobRequest\x12\x1f\n" +
	"\vrunner_kind\x18\x01 \x01(\tR\n" +
	"runnerKind\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\"R\n" +
	"\x0eGetJobResponse\x12\x17\n" +
	"\ahas_job\x18\x01 \x01(\bR\x06hasJob\x12'\n" +
	"\x0fassignment_json\x18\x02 \x01(\tR\x0eassignmentJson\"E\n" +
	"\rRunEventProto\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"event_json\x18\x02 \x01(\tR\teventJson\"&\n" +
	"\x14StreamEventsResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"i\n" +
	"\x13ReportStatusRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"&\n" +
	"\x14ReportStatusResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"6\n" +
	"\x13WatchCancelsRequest\x12\x1f\n" +
	"\vrunner_kind\x18\x01 \x01(\tR\n" +
	"runnerKind\"%\n" +
	"\fCancelSignal\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId2\xf7\x02\n" +
	"\rRunnerService\x12M\n" +
	"\x06GetJob\x12 .runkite.runner.v0.GetJobRequest\x1a!.runkite.runner.v0.GetJobResponse\x12[\n" +
	"\fStreamEvents\x12 .runkite.runner.v0.RunEventProto\x1a'.runkite.runner.v0.StreamEventsResponse(\x01\x12_\n" +
	"\fReportStatus\x12&.runkite.runner.v0.ReportStatusRequest\x1a'.runkite.runner.v0.ReportStatusResponse\x12Y\n" +
	"\fWatchCancels\x12&.runkite.runner.v0.WatchCancelsRequest\x1a\x1f.runkite.runner.v0.CancelSignal0\x01B;Z9github.com/sharanharsoor/runkite/internal/bridge/runnerpbb\x06proto3"

var (
	file_runner_proto_rawDescOnce sync.Once
	file_runner_proto_rawDescData []byte
)

func file_runner_proto_rawDescGZIP() []byte {
	file_runner_proto_rawDescOnce.Do(func() {
		file_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runner_proto_rawDesc), len(file_runner_proto_rawDesc)))
	})
	return file_runner_proto_rawDescData
}

var file_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_runner_proto_goTypes = []any{
	(*GetJobRequest)(nil),        // 0: runkite.runner.v0.GetJobRequest
	(*GetJobResponse)(nil),       // 1: runkite.runner.v0.GetJobResponse
	(*RunEventProto)(nil),        // 2: runkite.runner.v0.RunEventProto
	(*StreamEventsResponse)(nil), // 3: runkite.runner.v0.StreamEventsResponse
	(*ReportStatusRequest)(nil),  // 4: runkite.runner.v0.ReportStatusRequest
	(*ReportStatusResponse)(nil), // 5: runkite.runner.v0.ReportStatusResponse
	(*WatchCancelsRequest)(nil),  // 6: runkite.runner.v0.WatchCancelsRequest
	(*CancelSignal)(nil),         // 7: runkite.runner.v0.CancelSignal
}
var file_runner_proto_depIdxs = []int32{
	0, // 0: runkite.runner.v0.RunnerService.GetJob:input_type -> runkite.runner.v0.GetJobRequest
	2, // 1: runkite.runner.v0.RunnerService.StreamEvents:input_type -> runkite.runner.v0.RunEventProto
	4, // 2: runkite.runner.v0.RunnerService.ReportStatus:input_type -> runkite.runner.v0.ReportStatusRequest
	6, // 3: runkite.runner.v0.RunnerService.WatchCancels:input_type -> runkite.runner.v0.WatchCancelsRequest
	1, // 4: runkite.runner.v0.RunnerService.GetJob:output_type -> runkite.runner.v0.GetJobResponse
	3, // 5: runkite.runner.v0.RunnerService.StreamEvents:output_type -> runkite.runner.v0.StreamEventsResponse
	5, // 6: runkite.runner.v0.RunnerService.ReportStatus:output_type -> runkite.runner.v0.ReportStatusResponse
	7, // 7: runkite.runner.v0.RunnerService.WatchCancels:output_type -> runkite.runner.v0.CancelSignal
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_runner_proto_init() }
func file_runner_proto_init() {
	if File_runner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runner_proto_rawDesc), len(file_runner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runner_proto_goTypes,
		DependencyIndexes: file_runner_proto_depIdxs,
		MessageInfos:      file_runner_proto_msgTypes,
	}.Build()
	File_runner_proto = out.File
	file_runner_proto_goTypes = nil
	file_runner_proto_depIdxs = nil
}
