apiVersion: v1
kind: Service
metadata:
  name: {{ include "runkite.fullname" . }}
  labels:
    {{- include "runkite.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      appProtocol: http
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      appProtocol: kubernetes
  selector:
    {{- include "runkite.selectorLabels" . | nindent 4 }}
