# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import runner_pb2 as runner__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in runner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RunnerServiceStub(object):
    """RunnerService is the gRPC service that runners implement.
    The control plane connects to runners (long-poll style) or runners
    connect to the control plane -- either way, this is the contract.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetJob = channel.unary_unary(
                '/runkite.runner.v0.RunnerService/GetJob',
                request_serializer=runner__pb2.GetJobRequest.SerializeToString,
                response_deserializer=runner__pb2.GetJobResponse.FromString,
                _registered_method=True)
        self.StreamEvents = channel.stream_unary(
                '/runkite.runner.v0.RunnerService/StreamEvents',
                request_serializer=runner__pb2.RunEventProto.SerializeToString,
                response_deserializer=runner__pb2.StreamEventsResponse.FromString,
                _registered_method=True)
        self.ReportStatus = channel.unary_unary(
                '/runkite.runner.v0.RunnerService/ReportStatus',
                request_serializer=runner__pb2.ReportStatusRequest.SerializeToString,
                response_deserializer=runner__pb2.ReportStatusResponse.FromString,
                _registered_method=True)
        self.WatchCancels = channel.unary_stream(
                '/runkite.runner.v0.RunnerService/WatchCancels',
                request_serializer=runner__pb2.WatchCancelsRequest.SerializeToString,
                response_deserializer=runner__pb2.CancelSignal.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/runkite.runner.v0.RunnerService/Heartbeat',
                request_serializer=runner__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=runner__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class RunnerServiceServicer(object):
    """RunnerService is the gRPC service that runners implement.
    The control plane connects to runners (long-poll style) or runners
    connect to the control plane -- either way, this is the contract.
    """

    def GetJob(self, request, context):
        """GetJob blocks until a job is available for the runner.
        Runner calls this in a loop (long-poll pattern).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request_iterator, context):
        """StreamEvents is called by the runner to stream events back
        to the control plane for a specific run.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportStatus(self, request, context):
        """ReportStatus reports the final status of a run.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchCancels(self, request, context):
        """WatchCancels is a server-streaming RPC the runner calls to receive
        cancel signals for runs it is executing. The runner sends its
        runner_kind; the server streams CancelSignal messages whenever
        a run of that kind is cancelled.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeat is called periodically by the runner while a run is
        actively executing, to prove liveness for the WHOLE run, not just
        delivery (plans/pending_items.md item 16, Problem 2). Without this,
        the control plane only knows a job is alive up to its first
        StreamEvents message (~15ms after dequeue in practice) -- a runner
        crash any time after that left the run permanently stuck, confirmed
        live. The server extends the same in-flight lease Dequeue creates
        (see transport.JobQueue's Renew) each time this arrives; a runner
        that stops heartbeating (crashed, or an older runner that doesn't
        send this RPC at all) eventually falls stale and gets reclaimed by
        the existing ReclaimStale reaper -- no new reclaim mechanism needed,
        just a mechanism to keep resetting the clock during real work.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RunnerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=runner__pb2.GetJobRequest.FromString,
                    response_serializer=runner__pb2.GetJobResponse.SerializeToString,
            ),
            'StreamEvents': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=runner__pb2.RunEventProto.FromString,
                    response_serializer=runner__pb2.StreamEventsResponse.SerializeToString,
            ),
            'ReportStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportStatus,
                    request_deserializer=runner__pb2.ReportStatusRequest.FromString,
                    response_serializer=runner__pb2.ReportStatusResponse.SerializeToString,
            ),
            'WatchCancels': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchCancels,
                    request_deserializer=runner__pb2.WatchCancelsRequest.FromString,
                    response_serializer=runner__pb2.CancelSignal.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=runner__pb2.HeartbeatRequest.FromString,
                    response_serializer=runner__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'runkite.runner.v0.RunnerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('runkite.runner.v0.RunnerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RunnerService(object):
    """RunnerService is the gRPC service that runners implement.
    The control plane connects to runners (long-poll style) or runners
    connect to the control plane -- either way, this is the contract.
    """

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runkite.runner.v0.RunnerService/GetJob',
            runner__pb2.GetJobRequest.SerializeToString,
            runner__pb2.GetJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/runkite.runner.v0.RunnerService/StreamEvents',
            runner__pb2.RunEventProto.SerializeToString,
            runner__pb2.StreamEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runkite.runner.v0.RunnerService/ReportStatus',
            runner__pb2.ReportStatusRequest.SerializeToString,
            runner__pb2.ReportStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchCancels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/runkite.runner.v0.RunnerService/WatchCancels',
            runner__pb2.WatchCancelsRequest.SerializeToString,
            runner__pb2.CancelSignal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runkite.runner.v0.RunnerService/Heartbeat',
            runner__pb2.HeartbeatRequest.SerializeToString,
            runner__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
