# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: runner.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'runner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crunner.proto\x12\x11runkite.runner.v0\"=\n\rGetJobRequest\x12\x13\n\x0brunner_kind\x18\x01 \x01(\t\x12\x17\n\x0ftimeout_seconds\x18\x02 \x01(\x05\":\n\x0eGetJobResponse\x12\x0f\n\x07has_job\x18\x01 \x01(\x08\x12\x17\n\x0f\x61ssignment_json\x18\x02 \x01(\t\"3\n\rRunEventProto\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\x12\n\nevent_json\x18\x02 \x01(\t\"\"\n\x14StreamEventsResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"L\n\x13ReportStatusRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\"\"\n\x14ReportStatusResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"*\n\x13WatchCancelsRequest\x12\x13\n\x0brunner_kind\x18\x01 \x01(\t\"\x1e\n\x0c\x43\x61ncelSignal\x12\x0e\n\x06run_id\x18\x01 \x01(\t2\xf7\x02\n\rRunnerService\x12M\n\x06GetJob\x12 .runkite.runner.v0.GetJobRequest\x1a!.runkite.runner.v0.GetJobResponse\x12[\n\x0cStreamEvents\x12 .runkite.runner.v0.RunEventProto\x1a\'.runkite.runner.v0.StreamEventsResponse(\x01\x12_\n\x0cReportStatus\x12&.runkite.runner.v0.ReportStatusRequest\x1a\'.runkite.runner.v0.ReportStatusResponse\x12Y\n\x0cWatchCancels\x12&.runkite.runner.v0.WatchCancelsRequest\x1a\x1f.runkite.runner.v0.CancelSignal0\x01\x42\x35Z3github.com/runkite/runkite/internal/bridge/runnerpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'runner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3github.com/runkite/runkite/internal/bridge/runnerpb'
  _globals['_GETJOBREQUEST']._serialized_start=35
  _globals['_GETJOBREQUEST']._serialized_end=96
  _globals['_GETJOBRESPONSE']._serialized_start=98
  _globals['_GETJOBRESPONSE']._serialized_end=156
  _globals['_RUNEVENTPROTO']._serialized_start=158
  _globals['_RUNEVENTPROTO']._serialized_end=209
  _globals['_STREAMEVENTSRESPONSE']._serialized_start=211
  _globals['_STREAMEVENTSRESPONSE']._serialized_end=245
  _globals['_REPORTSTATUSREQUEST']._serialized_start=247
  _globals['_REPORTSTATUSREQUEST']._serialized_end=323
  _globals['_REPORTSTATUSRESPONSE']._serialized_start=325
  _globals['_REPORTSTATUSRESPONSE']._serialized_end=359
  _globals['_WATCHCANCELSREQUEST']._serialized_start=361
  _globals['_WATCHCANCELSREQUEST']._serialized_end=403
  _globals['_CANCELSIGNAL']._serialized_start=405
  _globals['_CANCELSIGNAL']._serialized_end=435
  _globals['_RUNNERSERVICE']._serialized_start=438
  _globals['_RUNNERSERVICE']._serialized_end=813
# @@protoc_insertion_point(module_scope)
